apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: planet9-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: planet9-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50