apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: planet9-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: planet9-deployment
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1000m
          memory: 1Gi
        maxAllowed:
          cpu: 2000m
          memory: 1Gi
        controlledResources: ["cpu", "memory"]